//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMaquila.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario()
        {
            this.produccion_terminada = new HashSet<produccion_terminada>();
        }
        [Display(Name = "id")]
        public int id { get; set; }
        [Display(Name = "producto")]
        public string producto { get; set; }
        [Display(Name = "cantidad")]
        public Nullable<int> cantidad { get; set; }
        [Display(Name = "descripcion")]
        public string descripcion { get; set; }
        [Display(Name = "precio")]
        public Nullable<decimal> precio { get; set; }
        [Display(Name = "canidad minima necesaria")]
        public Nullable<int> MOQ { get; set; }
        [Display(Name = "proveedor(FK)")]
        public Nullable<int> id_proveedores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produccion_terminada> produccion_terminada { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
