//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMaquila.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class produccion_terminada
    {
        [Display(Name = "id")]
        public int id { get; set; }
        [Display(Name = "nombre de la prenda")]
        public string prenda_terminada { get; set; }
        [Display(Name = "fecha")]
        public Nullable<System.DateTime> fecha_fabricacion { get; set; }
        [Display(Name = "cantidad")]
        public Nullable<int> cantidad { get; set; }
        [Display(Name = "cliente(FK)")]
        public Nullable<int> id_cliente { get; set; }
        [Display(Name = "departamento asignado(FK)")]
        public Nullable<int> id_departamento { get; set; }
        [Display(Name = "producto mas usado(FK)")]
        public Nullable<int> id_inventario { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual inventario inventario { get; set; }
    }
}
